### PR TITLE
Rename checklists.md to workshop-guide.md #39

### PR DESCRIPTION
**Pull request by arockenberger**
#39

### CODE REVIEW

**Comment by lexnederbragt** [comment]
The word 'checklist' is derived from the Carpentries Handbook, see https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html. So I would be in favour of keeping it, maybe use Workshop Checklists instead. But it is not a big issue to me...

**Comment by desireetreichler** [comment]
I agree with both of you. The Carpentries however have a nested setup with an index page (called index.md by them) with general information and a table of content with links to all the checklists . Our UiO setup is somewhat less complicated and I thus don't think it matters so much what the file is called. But whatever name we use, it would be useful if it is consistent - i.e. file name and links in index/readme files further up in the hierarchy should be somewhat related.

Example: https://github.com/uio-carpentry/organisational -> this links to checklists. Either change this (and possibly other places) also to Workshop Guide, or keep checklist somewhere in the file name.

**Comment by arockenberger** [comment]
OK – it looks like this is not a straight-forward one.
If I were to change the filename to "workshop-guide", I would also update the links in other documents that refer to it.
I still think calling the document "checklists" is too unspecific, especially given that we have an actual checklist with the onboarding-checklist.

**Comment by lexnederbragt** [comment]
On further considerations I think workshop guide is OK.

**Comment by arockenberger** [comment]
Let’s go for it and see!

**Pull request merged**
